//! Pattern lists — safe, dangerous, deny, and admin command patterns.
//!
//! Design follows Claude Code's model: flag everything suspicious,
//! let the user decide; never silently block. Only the fork bomb
//! is auto-denied (can crash the system before user can react).

/// Patterns that are ALWAYS blocked (all levels).
pub(crate) fn deny_patterns() -> Vec<String> {
    vec![":(){ :|:& };:".into()]
}

/// Patterns flagged as "dangerous" — user must CONFIRM at SemiAuto.
pub(crate) fn dangerous_patterns() -> Vec<String> {
    vec![
        // ── Privilege Escalation ──────────────────────────────────────
        "chmod +s".into(),
        "chmod u+s".into(),
        "chmod g+s".into(),
        "chmod 4".into(),
        "chmod 777".into(),
        "chmod -R".into(),
        "chown".into(),
        "icacls * /grant".into(),
        "icacls * /setowner".into(),
        // ── Reverse Shells ────────────────────────────────────────────
        "/dev/tcp/".into(),
        "/dev/udp/".into(),
        "mkfifo".into(),
        "nc -e".into(),
        "nc -c".into(),
        "socat exec:".into(),
        "socat EXEC:".into(),
        // ── Network Recon & Scanning ──────────────────────────────────
        "nmap".into(),
        "masscan".into(),
        "nc ".into(),
        "netcat".into(),
        "tcpdump".into(),
        "wireshark".into(),
        "tshark".into(),
        // ── Data Exfiltration ─────────────────────────────────────────
        "scp ".into(),
        "sftp ".into(),
        "rsync ".into(),
        // ── Mass Destruction ──────────────────────────────────────────
        "rm -rf /*".into(),
        "rm -rf /".into(),
        "rm -rf / *".into(),
        "rm -rf ~".into(),
        "rm -rf $HOME".into(),
        "rm -rf .".into(),
        "del /f /s C:\\".into(),
        "del /f /s D:\\".into(),
        "format C:".into(),
        "format D:".into(),
        "dd if=* of=/dev/sd".into(),
        "dd if=* of=/dev/nvme".into(),
        "dd if=* of=/dev/xvd".into(),
        "dd if=* of=/dev/vd".into(),
        "reg delete HKLM".into(),
        // ── Recursive Deletion ────────────────────────────────────────
        "rm -rf".into(),
        "rm -r".into(),
        "del /f /s".into(),
        "Remove-Item -Recurse -Force".into(),
        // ── System Services ───────────────────────────────────────────
        "systemctl".into(),
        "sc stop".into(),
        "sc start".into(),
        "sc config".into(),
        "net stop".into(),
        "net start".into(),
        // ── Package Installation ──────────────────────────────────────
        "pip install".into(),
        "npm install -g".into(),
        "cargo install".into(),
        "apt install".into(),
        "apt-get install".into(),
        "brew install".into(),
        "choco install".into(),
        "winget install".into(),
        "yum install".into(),
        "dnf install".into(),
        "pacman -S".into(),
        // ── Network ───────────────────────────────────────────────────
        "curl ".into(),
        "wget ".into(),
        "Invoke-WebRequest".into(),
        // ── Code Injection ────────────────────────────────────────────
        "eval ".into(),
        "exec ".into(),
        "iex ".into(),
        "Invoke-Expression".into(),
        // ── Payload Obfuscation ───────────────────────────────────────
        "base64".into(),
        "xxd".into(),
        "openssl enc".into(),
        "FromBase64String".into(),
        "gunzip".into(),
        "gzip -d".into(),
        // ── Pipe to Interpreter ───────────────────────────────────────
        "| sh".into(),
        "| bash".into(),
        "| zsh".into(),
        "| fish".into(),
        "| python".into(),
        "| python3".into(),
        "| ruby".into(),
        "| perl".into(),
        "| lua".into(),
        "| node".into(),
        "| cmd".into(),
        "| powershell".into(),
        // ── Download + Pipe ───────────────────────────────────────────
        "curl * | sh".into(),
        "curl * | bash".into(),
        "wget * | sh".into(),
        "wget * -O - | sh".into(),
        "Invoke-WebRequest * | iex".into(),
        // ── Persistence ───────────────────────────────────────────────
        "crontab".into(),
        "schtasks".into(),
        "at ".into(),
        "rc.local".into(),
        "init.d".into(),
        ".bashrc".into(),
        ".profile".into(),
        ".zshrc".into(),
        "systemctl enable".into(),
        // ── Anti-Forensics ────────────────────────────────────────────
        "shred".into(),
        "wipe ".into(),
        "history -c".into(),
        "Clear-History".into(),
        "wevtutil cl".into(),
        "vssadmin delete".into(),
        // ── Env Modification ─────────────────────────────────────────
        "export PATH=".into(),
        "setx PATH".into(),
        // ── Docker — Privileged & Escape ──────────────────────────────
        "docker run --privileged".into(),
        "docker run --pid=host".into(),
        "docker run --network=host".into(),
        "docker run --cap-add=SYS_ADMIN".into(),
        "docker run --cap-add=ALL".into(),
        "docker run --security-opt label=disable".into(),
        "docker run --security-opt apparmor=unconfined".into(),
        "docker run --security-opt seccomp=unconfined".into(),
        "docker run -v /:/host".into(),
        "docker run -v /:/".into(),
        "docker run --device=/dev/".into(),
        "docker run --ipc=host".into(),
        // ── Docker — Destructive ───────────────────────────────────────
        "docker rm -f".into(),
        "docker system prune -af".into(),
        "docker system prune -a".into(),
        "docker volume prune -f".into(),
        "docker compose down -v".into(),
        "docker exec".into(),
        // ── Git Force ─────────────────────────────────────────────────
        "git push --force".into(),
        "git push -f".into(),
        "git reset --hard".into(),
        // ── Windows-Specific ──────────────────────────────────────────
        "Set-MpPreference".into(),
        "netsh".into(),
        "bcdedit".into(),
        "reg add".into(),
        "reg delete".into(),
        "wevtutil".into(),
        "vssadmin".into(),
        "wbadmin".into(),
        // ── Firewall Modification ─────────────────────────────────────
        "iptables".into(),
        "nft ".into(),
        "ufw ".into(),
        "firewall-cmd".into(),
        // ── Path Traversal ────────────────────────────────────────────
        "../etc/".into(),
        "../shadow".into(),
        "../passwd".into(),
        "../ssh/".into(),
        "system32/config".into(),
        "system32\\config".into(),
        "..\\..\\windows".into(),
    ]
}

/// Patterns that are ALWAYS safe (auto-approve at SemiAuto).
pub(crate) fn safe_patterns() -> Vec<String> {
    vec![
        "git status".into(),
        "git diff".into(),
        "git log".into(),
        "git branch".into(),
        "git add".into(),
        "git commit".into(),
        "git pull".into(),
        "git push".into(),
        "git fetch".into(),
        "git checkout".into(),
        "git stash".into(),
        "cat ".into(),
        "type ".into(),
        "head ".into(),
        "tail ".into(),
        "less ".into(),
        "more ".into(),
        "ls".into(),
        "dir".into(),
        "tree".into(),
        "cargo build".into(),
        "cargo test".into(),
        "cargo check".into(),
        "cargo run".into(),
        "cargo fmt".into(),
        "cargo clippy".into(),
        "npm run".into(),
        "npm test".into(),
        "npm build".into(),
        "make ".into(),
        "cmake ".into(),
        "echo ".into(),
        "print".into(),
        "which ".into(),
        "where ".into(),
        "whoami".into(),
        "pwd".into(),
        "date".into(),
        "env".into(),
        "printenv".into(),
        "pip list".into(),
        "pip show".into(),
        "npm list".into(),
        "cargo search".into(),
        "cp ".into(),
        "copy ".into(),
        "mv ".into(),
        "move ".into(),
        "mkdir ".into(),
        "touch ".into(),
        "Get-ChildItem".into(),
        "Get-Content".into(),
        "Set-Location".into(),
        "Write-Output".into(),
    ]
}

/// Commands requiring admin/sudo — NEVER auto-approved even at FullyAuto.
pub(crate) fn admin_patterns() -> Vec<String> {
    vec![
        "sudo ".into(),
        "su ".into(),
        "runas ".into(),
        "RunAs".into(),
        "Start-Process -Verb RunAs".into(),
        "pkexec ".into(),
    ]
}
